spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  org.superbiz.moviefun: INFO
  org.superbiz.moviefun.movies: DEBUG

s3:
  accessKey: <access key id>
  secretKey: <secret access key>
  bucketName: <name of the bucket>
