spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root

  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp

logging.level:
  root: WARN
  org.superbiz: DEBUG

s3:
  endpointUrl: <aws endpoint>
  accessKey: <access key id>
  secretKey: <secret access key>
  bucketName: <name of the bucket>

rabbitmq:
  uri: amqp://guest:guest@localhost
  queue: my-rabbit-queue
